name: The test

on:
  push:
    branches:
      - main

jobs:
  test_vi:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: test vi
        run: |
          sudo mkdir -p /.test
          sudo chmod 777 /.test
          cd /.test
          echo '{' >> test.json
          echo '"development":{' >> test.json
          echo '"username":"root"' >> test.json
          echo ',"password":"1234qwer"' >> test.json
          echo ',"host":"127.0.0.1"' >> test.json
          echo ',"database":"test"' >> test.json
          echo ',"dialect":"mysql"}' >> test.json
          echo '}' >> test.json

      - name: test_look vi
        run: |
          cd /.test
          cat test.json
