name: The test

on:
  push:
    branches:
      - main

jobs:
  test_vi:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: test vi
        run: |
          mkdir -p ~/test
          chmod 777 ~/test
          cd ~/test
          touch tester
          vi tester -e
          i
          12345
          dsdads
          zzzzz
          :wq

      - name: test_look vi
        run: |
          cd ~/test
          ls -l | tee tester
